### ISSUE TITLE
I like this very much!! Random Thoughts....

### ISSUE THREAD

**Issue by khchen** [indiscipline/tetronimia#1]
**Basic**
- Add dependencies into nimble file (zero_functional, cligen, etc..). 

**Advanced**
- Rotate both clockwise and counterclockwise.
- HoldBox and NextBox can be draw on screen instead of just a letter.
- More than one next piece.
- Configurable key mapping.

**Mission: Impossible**
- https://tetris.fandom.com/wiki/SRS
- https://tetris.fandom.com/wiki/Tetris_Guideline

Anyway, thanks for your effort.

**Comment by kaushalmodi** [comment]
> Configurable key mapping.

May be through a `config.toml` file? `parsetoml` nimble package can be used to parse that. Or, simply as switches.. people can create shell aliases that always pass those key mapping switches.

**Comment by indiscipline** [comment]
Thanks for you feedback!

@kaushalmodi already fixed the nimble file, so that's one off the list

Regarding SRS and other guidelines. I'm fully aware of their existence and I addressed them for reminding me some game mechanics but considering:
1. They are are product of a particular commercial entity prepared for asserting some level of control over their licensees.
2. They are just overly complicated and introduce additional levels of gameplay which aren't easily discoverable.

I don't think they suit Tetronimia, as this is orthogonal to the overall spirit of the project.

However, I'm going to prepare a couple of separate PRs with feature requests to catch any possible interest from the users.

Regarding showing next and held pieces drawn instead of letters: I considered implementing this, but I also wanted to be able to easily resize the playing field to any width (possibly, via switches). In case of resizing to the full terminal width this requires shifting the figure placement somewhere, or dynamically falling back to displaying them in the status line. Also, this makes a game less unforgiving.

**Comment by indiscipline** [comment]
Regarding showing more than one next Tetronimo: certainly doable, but do players really need it? From my point of view, at lower levels it doesn't really matter as the speed allows for careful planning, especially with the Hold Box enabled. However, the speed increases fairly rapidly and even from the mid-levels you have not enough time to plan more than one piece ahead (or do you?), later you can't be able to even glance at the single next piece. Also, when using the Hold Box, one next piece is all you need to make a proper decision to use it or not.

If you think this reasoning is wrong, please, open a separate FR.

**Comment by indiscipline** [comment]
There's now separate FR issues for some of the other requests:
- FR: Support configurable key mapping: #7
- FR: support clockwise rotation or both: #6
- FR: Support additional rotation schemes such as SRS: #5

@khchen and others, if you really want to see any of the features implemented, drop by those please.
